### ISSUE TITLE
User agent unauthorized

### ISSUE THREAD

**Issue by jpiron** [philippmeisberger/ddns-updater#4]
Hi,

I'm trying to automate the installation of ddns-updater with Ansible and the user-agent the [apt_key module](https://docs.ansible.com/ansible/latest/apt_key_module.html) uses (Python-urllib) is unauthorized by your apache server.
I get a HTTP 403 running the following:
```bash
wget --user-agent='Python-urllib' http://apt.pm-codeworks.de/pm-codeworks.de.gpg
```
while
```bash
wget --user-agent='Mozilla' http://apt.pm-codeworks.de/pm-codeworks.de.gpg
```
works fine.

Could you authorize the Python-urllib user agent for the http://apt.pm-codeworks.de/pm-codeworks.de.gpg resource ?

**Comment by philippmeisberger** [comment]
Hey,
I am really sorry but my webhoster does not provide any way to do this.

**Comment by jpiron** [comment]
Ok no problem I'll manage a workaround on the Ansible side then :)
